# Generated by Django 6.0.3 on 2026-04-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('qualification', models.CharField(choices=[('10th Pass', '10th Pass'), ('12th Pass', '12th Pass'), ('B.Sc', 'B.Sc'), ('B.Com', 'B.Com'), ('B.A', 'B.A'), ('M.Sc', 'M.Sc'), ('M.Com', 'M.Com'), ('M.A', 'M.A')], max_length=50)),
                ('course', models.CharField(choices=[('MLT (Medical Lab Technology)', 'MLT (Medical Lab Technology)'), ('GRD (General Radiology & Diagnosis)', 'GRD (General Radiology & Diagnosis)')], max_length=255)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
